export const ROOT_ROUTES = {
  SPLASH: 'Splash' as 'Splash',
  MAIN_APP: 'MainApp' as 'MainApp',
  FAQ: 'Faq' as 'Faq',
  TERMS_AND_CONDITIONS: 'TermsAndConditions' as 'TermsAndConditions',
};

export const LOGGED_OUT_ROUTES = {
  LOGIN: 'Login' as 'Login',
  REGISTER: 'Register' as 'Register',
  FORGET_PASSWORD: 'ForgetPassword' as 'ForgetPassword',
  DOCUMENT_UPLOAD: 'DocumentUpload' as 'DocumentUpload',
  SIGN_UP_EXTRA_INFO: 'SignUpExtraInfo' as 'SignUpExtraInfo',
  PHONE_VERIFICATION: 'PhoneVerification' as 'PhoneVerification',
  OTP: 'Otp' as 'Otp',
  ON_BOARDING: 'OnBoarding' as 'OnBoarding',
  LICENSE_DETAILS: 'LicenseDetails' as 'LicenseDetails',
};
export const LOGGED_IN_ROUTES = {
  HOME: 'Home' as 'Home',
  HOME_STACK: 'HomeStack' as 'HomeStack',
  CHANGE_PASSWORD: 'ChangePassword' as 'ChangePassword',
  ACCEPTED_JOBS: 'AcceptedJobs' as 'AcceptedJobs',
  ACTIVE_JOBS: 'ActiveJobs' as 'ActiveJobs',
  CHAT: 'Chat' as 'Chat',
  TASK_JOBS: 'TaskJobs' as 'TaskJobs',
  TAKE_OWNERSHIP_BY_QR_CODE: 'TakeOwnershipByQrCode' as 'TakeOwnershipByQrCode',
  NOTIFICATION: 'Notification' as 'Notification',
  NOTIFICATION_SETTINGS: 'NotificationSettings' as 'NotificationSettings',
  APP_NOTIFICATION: 'AppNotification' as 'AppNotification',
  PUSH_NOTIFICATION: 'PushNotification' as 'PushNotification',
  EMAIL_NOTIFICATION: 'EmailNotification' as 'EmailNotification',
  DELETE_ACCOUNT: 'DeleteAccount' as 'DeleteAccount',
  CONFIRM_DELETE_ACCOUNT: 'ConfirmDeleteAccount' as 'ConfirmDeleteAccount',
  SESSIONS_SUMMARY: 'SessionsSummary' as 'SessionsSummary',
  PROFILE: 'Profile' as 'Profile',
  SCAN_QR_CODE: 'ScanQrCode' as 'ScanQrCode',
  SCAN_BARCODE: 'ScanBarcode' as 'ScanBarcode',
  PAYMENT: 'Payment' as 'Payment',
  JOB_DETAILS: 'JobDetails' as 'JobDetails',
  ADD_SIGNATURE: 'AddSignature' as 'AddSignature',
  READY_DELIVERY: 'ReadyDelivery' as 'ReadyDelivery',
  ORDER_DELIVERY: 'OrderDelivery' as 'OrderDelivery',
  NOT_DELIVERED: 'NotDelivered' as 'NotDelivered',
  EDIT_PROFILE: 'EditProfile' as 'EditProfile',
  CHAT_EXPORT: 'ChatExport' as 'ChatExport',
  PAYMENT_HISTORY: 'PaymentHistory' as 'PaymentHistory',
  PROFILE_REPORTS: 'ProfileReports' as 'ProfileReports',
  REPORT_VIEW: 'ReportView' as 'ReportView',
  UPCOMING_JOBS: 'UpcomingJobs' as 'UpcomingJobs',
  URGENT_JOBS: 'UrgentJobs' as 'UrgentJobs',
  AVAILABLE_DRIVERS: 'AvailableDrivers' as 'AvailableDrivers',
  TRANSFERRED_JOB: 'TransferredJob' as 'TransferredJob',
};
